### PR TITLE
Rescues from errors that were beign thrown by Artifact#ov_asset when Art...

### PR DESCRIPTION
**Pull request by afred**
...ifact#pid does not exist in Fedora.

### CODE REVIEW

**Comment by afred** [comment]
@Muraszko This PR handles the errors that were being thrown by non-existent PIDs. Here are the new screens you'll see in such cases. Give me a :+1: or :-1:.

image

image

image

**Comment by Muraszko** [comment]
@afred 
 :+1:   Looks good, better solution then just wiping them out especially if we have to ever re-ingest all the records again.

**Comment by afred** [comment]
@mccalluc confirm PR sanity, and merge when Travis is green, por favor?

**Comment by afred** [comment]
@mccalluc ^^ or how about just a thumbs up, and I'll merge myself when Travis passes -- it's hanging on  a Capybara/Poltergeist-related thing I think.

**Pull request merged**
